### ISSUE TITLE
Incomplete mime_type data for several ContentTypes

### ISSUE THREAD

**Issue by Nicba1010** [google/magika#816] opened 2024-11-22 22:17 UTC
I do no know if this is by design, but some `ContentType`s seem to be missing their associated `mime_type` values.

e.g. the MKV content type specifies its `mime_type` as `None` instead of `video/x-matroska`

**Comment by reyammer** [comment] 2024-11-26 13:46
Thanks for reporting! If a content type that is actually used by any of the model has any of the metadata set to None, that's not by design. But I just checked MKV, and it has the correct mime_type (see https://github.com/google/magika/blob/main/assets/content_types_kb.min.json)? where did you see its mime_type to None?

Are you maybe checking an old version of the metadata?

**Comment by Nicba1010** [comment] 2024-11-26 14:27
Well I'm using the magika Python package (version `0.5.1`) on Python `3.12`.

This is the code I used to print all the MIME Types.

```python
from magika.content_types import ContentTypesManager


def get_mime_type_list() -> list[str]:
    return list({
        str(content_type.mime_type)
        for name, content_type
        in ContentTypesManager().cts.items()
        if content_type.mime_type is not None
    })

if __name__ == '__main__':
    for mime_type in get_mime_type_list():
        print(mime_type)
```

Also second question, I see that on `0.6.0rc3` the ContentTypesManager is gone. I can't seem to find it to test this with `0.6.0rc3`.

**Comment by Nicba1010** [comment] 2024-12-09 16:36
All good, thanks for replying at all. I send it out to the frontend of my app because a user can type in a mime type into a field and this is how I verify it actually exists. Might be quite a niche use case though and there are probably better solutions.

**Comment by reyammer** [comment] 2024-12-10 10:30
I see, interesting. In general I believe the knowledge base of types may useful for use cases like yours, so I see a good argument to expose it in some way or another. Maybe we could add some methods to the `Magika` class itself, something that would allow you to "get all content types" (getting a list of `ContentTypeLabel` (which is an enum), and then another method to query the metadata associated to each of them. Opened #826 to track this. Closing this one as I believe we clarified why things were missing; feel free to re-open and follow up if something is still not clear. Thanks!

**Closed by reyammer** 2024-12-10 10:30 UTC
